language: node_js
node_js:
- '8'
sudo: required
env:
- CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
script:
- node ./dist/index.js &
- node ./postman/test.js
deploy:
  provider: heroku
  app: hypercontract
  api_key:
    secure: ZFxghOQuRkxW5mycakBI0v4rHm2h1dm++lD0oTkFY1tJpCjhH61xDyYfEPmWTS1q1UO0izMmrQhY11itFpfdGoNug0yyt0+8FGZYFMU0jqDNIV3J8GkzxdoGRt4wF/fyOBpBRQ3R6WZnTpUDDg/anBjy84Jtt3IjJki4RbJbUgblf6GmS1aBZ2TBGF4IxikBBRYvRozdCNKfHNbAy35uB2L8QQtQYe9weBl6u5nhdadZN1W7u8/PxUkGDNmCHrM+huJr6wdUTJ9RREzlB+vaiuV5ND6XVCDoF26RUh7wNWddTCXxKrZtSM9UqAUGBDeTNcVwdbnK7CwaKnY5cieHXX9LWf44h6bTBbXxyGRV6rRqhKdmnNU7RJOuAZ2p5mcme8IBFxWElIZ6E+i7dXJt4hIGV9UnuzGzd2z5xDGLx+QOmwWu63dXuLveCiCG6LG+3sLloK20m2TvUjYKdcDq/+Eflpo2W1+RLyEjnJ5b2dWOktKGSY5NV5M7orB6ZR4q9xzfztgImw4Gy/iCAUc5yhGTBHwCPpaYLr4VhtfDbr2+GoZc7xbprsEAAVFQa5XAfeXAMKHkWVr1wFH94cHASerGW8W/IjZXci2prR5ek7Ak7Xa3G+xT31EWB+18RmYPIzPKYp1/ubO9XuKP98VtinNMxvwuDXv9rjAEdF46/AI=
