language: node_js
node_js:
- '8'
sudo: required
env:
- CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
script:
- node ./dist/index.js &
- node ./postman/test.js
deploy:
  provider: heroku
  app: hypercontract
  api_key:
    secure: FiUPgc1f3y6jWGs49Tpek8m7HoCvnqJIKK8IzAVEQAPhskGTZIuCDYf9LkriiI1DHb7nwidC1C0xqNcGtFkgqllQJf6AyDSiI3faLcXwelmWb1XwtDKDB/HQpTMus7qy/CK8Sc2BEKKIbxPd5jIWepV/TIoXBcUxo+TPZ76vh3CIFetc4rcfIKBbjJWuEFzlObHjRmwtUy/3xSJA9OwoI78exqnJc4mh8HgVtKO/r/uMeNSzhbE2cjJiSl/VrDjkkXkwL1WyUp8kWK/OBvfz4Ucz07yXrzXsuj3e9C3nteVBGbK06Gr4Udks9qqepsSY7e4l9jym2dc1hMS62yqwVG/nbmHl6PpOt+76dHyf1Byvpr6V2AJWSoXvkqDx97L5IbBYOOl+Vggpz/j9BifLP2Ce8hpaXiHXDhwfpgVQJfNG4/81t5QPeSuG10a8NUDGtnmwtnh29jWYbaOQy738EGioblUfhnnUerDwq40dMqmbckJZGSZxzQbFHhLniA8T026+EtPJszAtWHVuuzz5OnnI3v+nlQp/v+Uu1bifkv3W+RvhCtz+b6PNx8RC3vzgVLIoJ5AkvImio4/ZR8Az8wYXQ6fKl0V7/6gQ0VIwXM0RFL5vzRm2+4GyjnNF/GqkVFqg36/8v9ryoBYaCFK777NUAiA+Sco0oTPQh95wohM=
