language: node_js
node_js:
  - "8"
sudo: required
env:
  - CXX=g++-4.9
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.9
script:
  - node ./dist/index.js &
  - npm run test:test