language: node_js
node_js:
- '8'
sudo: required
env:
- CXX=g++-4.9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
script:
- node ./dist/index.js &
- npm run test:test
deploy:
  provider: heroku
  api_key:
    secure: DKs8COH8TG1lFzIH4QdQheDSo8dlizLe9GDQvVNZxsUtfc1xgW9n1uanISxPzpC+qwYHFVHmaHVHDfGwbJZ+BwOsvRAk8cBnORn2MslHn7SpifWnugXpQmkwKwChOKHkFVgnk4bai/aAneEPZHZdPvv4leBrhcSgAuOc5l7tODri7ZU9pH34DO0Wa4gmYoQ9I0TpCaExu5isDJdSJV8qTb1h4L/4F3KFx6mqcn+bsvRwOjFaIVKEOnI32jVJT6px7+W4agKDzxeK62zlWmrPgCKA4a6/xr1lYCkrgJaFllEZar01viVYuOB+ZJFYPYi1QM/qxwJQ+roPVgwkBKy4d6H+kHqpAYx102mgmGKLrgaHa3Slt2sLb9NUrkRx/ADn2x7yHQ1YZkqo9ux/nmWg6HGBJGWtQQyYGMJmhQLs9/riTCHMfGd1WQJJaeLa4hQ4m1y9YS8BFKiqeloqkxHejrqZS1w2KUs9g3GEaf8rLIrGzGl4U93ue51VO22pBcKwhLfXhaGIFpm7MbS08bLqDYQ2cuD7knZtih+Guz0sPjFkp4Pzd0p/S+03IzXtzAq3/w2ruY0gESmy3tUJ4whCJRR87XppI+EBktfcX0v1KvBCfVoR3moD8U6iACPdg3y0fMiQcysWJMUP9q2Np9nICCEdtuU2dxiaZKH0GWnZyu0=
